import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../assets/image-library.js',import.meta.url),'utf8');
const context={window:{},document:{querySelectorAll:()=>[]},console,URL,Blob,setTimeout,clearTimeout};
vm.createContext(context);vm.runInContext(source,context,{filename:'image-library.js'});
const workflow=context.window.TWImageWorkflowState;
assert.ok(workflow&&typeof workflow.derive==='function','workflow state helper must be exported');
let state=workflow.derive({revisionBusy:false});
assert.equal(state.locked,false);
assert.equal(state.busy,false);
assert.equal(state.completionLocked,false);
assert.equal(state.showSpinner,false);
assert.equal('canApprove' in state,false,'retired candidate decision state must not survive');
state=workflow.derive({revisionBusy:true});
assert.equal(state.locked,true,'organizing must synchronously lock mutations');
assert.equal(state.showSpinner,true,'organizing must show spinner');
assert.equal(state.organizeLabel,'整理中…');
state=workflow.derive({revisionBusy:false,completionLocked:true});
assert.equal(state.locked,true,'completed image revision must permanently lock mutations');
assert.equal(state.busy,false,'completed lock is terminal read-only state, not an in-progress aria-busy state');
assert.equal(state.completionLocked,true);
assert.equal(state.lockedLabel,'修改已完成，修改功能已鎖定');
assert.match(source,/if\(flow\.locked&&drawing\)cancelDrawing\(\)/,'lock transition must cancel a drawing already in progress');
assert.match(source,/mouse:move[\s\S]{0,180}workflowLocked\(\)[\s\S]{0,120}cancelDrawing/,'mouse move must fail closed while locked');
assert.match(source,/mouse:up[\s\S]{0,180}workflowLocked\(\)[\s\S]{0,120}cancelDrawing/,'mouse up must fail closed while locked');
assert.match(source,/currentCompleted/,'completed state must derive from a nonarchived current-source revision');
assert.match(source,/is-completion-locked/,'locked mutation controls must expose recognizable lock feedback');
assert.match(source,/已完成並鎖定/,'completed confirmation must project an explicit terminal button label');
assert.match(source,/檢視標註細節/,'completed state must relabel the safe details action so it no longer promises editing');
assert.match(source,/is-completion-feedback/,'successful completion must trigger bounded visual feedback');
assert.match(source,/reviewPage/,'completion feedback owner must contain both the review workspace and the page-level new-request control');
assert.match(source,/completedRevisionId/,'completion response must update the exact revision captured before await');
assert.match(source,/data-image-workflow-mutation/,'dynamic detail mutation controls must participate in permanent lock projection');
console.log('[OK] IMAGE REVIEW busy lock and in-flight drawing cancellation contract passed.');
