[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'image_source_version_engine.ps1')
Add-Type -AssemblyName System.Drawing
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
$root=Join-Path ([IO.Path]::GetTempPath()) ('twwater-image-manifest-scope-'+[Guid]::NewGuid().ToString('N'));$source=Join-Path $root 'source';$preview=Join-Path $root 'preview';$archive=Join-Path $root 'archive';$sessions=Join-Path $root 'sessions';foreach($d in @($source,$preview,$archive,$sessions)){[void][IO.Directory]::CreateDirectory($d)};$keys=Join-Path $archive '.keys';[void][IO.Directory]::CreateDirectory($keys);$keyPath=Join-Path $keys 'image-command.key';[IO.File]::WriteAllBytes($keyPath,[byte[]](0..31));$id=[Guid]::NewGuid().ToString();$doc=Join-Path $preview $id;[void][IO.Directory]::CreateDirectory($doc);$sourcePath=Join-Path $source 'image.png';$candidate=Join-Path $doc 'candidate.png';$a=[Drawing.Bitmap]::new(8,8);try{$a.Save($sourcePath,[Drawing.Imaging.ImageFormat]::Png)}finally{$a.Dispose()};$b=[Drawing.Bitmap]::new($sourcePath);try{$b.SetPixel(2,2,[Drawing.Color]::Red);$b.Save($candidate,[Drawing.Imaging.ImageFormat]::Png)}finally{$b.Dispose()};$old=Hash $sourcePath;$new=Hash $candidate;$binding=[ordered]@{binding_id=[Guid]::NewGuid().ToString();issued_utc=[DateTime]::UtcNow.AddMinutes(-1).ToString('yyyy-MM-ddTHH:mm:ssZ');expires_utc=[DateTime]::UtcNow.AddHours(1).ToString('yyyy-MM-ddTHH:mm:ssZ');public_id=$id;relative_path='image.png';source_hash=$old;extension='png';source_width=8;source_height=8;regions='2,2,3,3'};$binding.binding_hmac=Get-TWWaterImageBindingHmac -Binding $binding -Key ([IO.File]::ReadAllBytes($keyPath));$manifest=[ordered]@{schema_version=2;document_id=$id;relative_path='image.png';source_path=$sourcePath;source_sha256=$old;candidate_path=$candidate;candidate_sha256=$new;source_size=@(8,8);roi_px=@(2,2,3,3);outside_roi_changed_pixels=[int64]0;validation_status='passed';external_api_used=$false;source_overwritten=$false;binding=$binding};$manifestPath=Join-Path $preview 'wrong-location.json';[IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 8),(New-Object Text.UTF8Encoding($false)))
try{$actual='';try{[void](Publish-TWWaterImageOutputFromManifest -ManifestPath $manifestPath -SourceRoot $source -PreviewRoot $preview -ArchiveRoot $archive -SessionRoot $sessions -CommandKeyPath $keyPath)}catch{$actual=$_.Exception.Message};Assert ($actual-eq'IMAGE_MANIFEST_SCOPE_INVALID') ("Expected IMAGE_MANIFEST_SCOPE_INVALID, got $actual");Assert ((Hash $sourcePath)-eq$old) 'Out-of-scope manifest changed source.';Write-Host '[OK] Image manifest is bound to its signed document preview directory.'}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
