<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/bootstrap.php';
function db_fail(string $m): never{fwrite(STDERR,"[FAIL] {$m}\n");exit(1);}function db_ok(bool $v,string $m):void{if(!$v)db_fail($m);}
$config=portal_config(false);if(!$config['ready'])db_fail('portal config unavailable');$db=portal_open_database($config);if(!portal_feedback_schema_available($db))db_fail('site feedback schema unavailable');if(!portal_feedback_snapshot_schema_available($db))db_fail('immutable site feedback snapshot schema unavailable');
function db_test_png(int $width,int $height,int $shade=255):string{$chunk=static function(string $type,string $data):string{return pack('N',strlen($data)).$type.$data.pack('H*',hash('crc32b',$type.$data));};$rows=str_repeat("\0".str_repeat(chr($shade).chr($shade).chr($shade),$width),$height);return "\x89PNG\r\n\x1a\n".$chunk('IHDR',pack('NNCCCCC',$width,$height,8,2,0,0,0)).$chunk('IDAT',gzcompress($rows,9)).$chunk('IEND','');}
$user=$db->query("SELECT TOP(1) user_id,username,display_name,role_code FROM dbo.auth_users WHERE is_active=1 ORDER BY CASE role_code WHEN 'reader' THEN 0 WHEN 'editor' THEN 1 ELSE 2 END,user_id")->fetch();if($user===false)db_fail('no active test actor');
$db->beginTransaction();
try{
 $created=portal_feedback_create_batch($db,$user,['title'=>'ROLLBACK 視覺需求整合測試']);$batch=$created['batch'];db_ok($batch['status_code']==='draft','batch must begin draft');
 $timeline=portal_feedback_list($db,$user);$timelineRow=null;foreach($timeline as $candidate){if($candidate['public_id']===$batch['public_id']){$timelineRow=$candidate;break;}}db_ok(is_array($timelineRow),'created batch must appear in the timeline');db_ok(array_key_exists('created_at',$timelineRow)&&array_key_exists('updated_at',$timelineRow)&&array_key_exists('completed_at',$timelineRow)&&array_key_exists('item_count',$timelineRow),'timeline row must expose dates and item count');
 $saved=portal_feedback_save_item($db,$user,['batch_id'=>$batch['public_id'],'target_url'=>'?action=documents','annotation_type'=>'rectangle','geometry'=>['x'=>.1,'y'=>.2,'width'=>.3,'height'=>.25],'viewport'=>['width'=>1200,'height'=>800,'scroll_x'=>0,'scroll_y'=>40,'dpr'=>1.25],'selector'=>'body > main > section:nth-of-type(1)','element_tag'=>'section','element_text'=>'文件清單','page_fingerprint'=>str_repeat('a',64),'element_fingerprint'=>str_repeat('b',64),'instruction'=>'把文件清單文字放大並減少左右留白']);
 db_ok(count($saved['batch']['items'])===1,'saved item must read back');$item=$saved['batch']['items'][0];db_ok($item['target_action']==='documents'&&$item['instruction_text']==='把文件清單文字放大並減少左右留白','saved item must preserve validated fields');
 $updated=portal_feedback_save_item($db,$user,['batch_id'=>$batch['public_id'],'item_id'=>$item['public_id'],'target_url'=>'?action=documents','annotation_type'=>'arrow','geometry'=>['x1'=>.1,'y1'=>.2,'x2'=>.7,'y2'=>.8],'viewport'=>['width'=>390,'height'=>844,'scroll_x'=>0,'scroll_y'=>200,'dpr'=>3],'selector'=>'#document-list','element_tag'=>'section','element_text'=>'文件清單','page_fingerprint'=>str_repeat('a',64),'element_fingerprint'=>str_repeat('b',64),'instruction'=>'箭頭所指的標題改為 20px']);db_ok($updated['batch']['items'][0]['annotation_type_code']==='arrow','item update must persist typed geometry');
 $deleted=portal_feedback_delete_item($db,$user,['batch_id'=>$batch['public_id'],'item_id'=>$item['public_id']]);db_ok(count($deleted['batch']['items'])===0,'soft-deleted item must disappear without DELETE permission');
 $marker=['batch_id'=>$batch['public_id'],'target_url'=>'?action=documents','annotation_type'=>'number','geometry'=>['x'=>.2,'y'=>.2,'width'=>.04,'height'=>.06],'viewport'=>['width'=>1200,'height'=>800,'scroll_x'=>0,'scroll_y'=>0,'dpr'=>1],'selector'=>'#document-list','element_tag'=>'section','element_text'=>'文件清單','page_fingerprint'=>str_repeat('c',64),'element_fingerprint'=>str_repeat('d',64)];
 $markerA=portal_feedback_save_item($db,$user,$marker+['instruction'=>'marker A']);$markerAId=$markerA['saved_item_id'];$markerB=portal_feedback_save_item($db,$user,$marker+['instruction'=>'marker B']);$markerBId=$markerB['saved_item_id'];portal_feedback_delete_item($db,$user,['batch_id'=>$batch['public_id'],'item_id'=>$markerAId]);$markerC=portal_feedback_save_item($db,$user,$marker+['instruction'=>'marker C']);
 db_ok(array_column($markerC['batch']['items'],'instruction_text')===['marker B','marker C'],'delete-create-save-reload order must preserve number-marker creation order even when sequence gaps are reused');
 $db->prepare("UPDATE dbo.site_feedback_batches SET status_code='rejected',revision_number=revision_number+1 WHERE public_id=CONVERT(uniqueidentifier,?)")->execute([$batch['public_id']]);
 $reopened=portal_feedback_save_item($db,$user,array_merge($marker,['item_id'=>$markerBId,'geometry'=>['x'=>.35,'y'=>.25,'width'=>.04,'height'=>.06],'instruction'=>'marker B moved after return']));
 db_ok($reopened['batch']['status_code']==='draft'&&$reopened['batch']['items'][0]['instruction_text']==='marker B moved after return'&&abs((float)$reopened['batch']['items'][0]['geometry']['x']-.35)<.000001,'a returned batch must be editable, persist moved geometry, and reopen as draft after its first saved change');
 $snapshotPayload=['batch_id'=>$batch['public_id'],'snapshot_kind'=>'before','revision_number'=>(int)$reopened['batch']['revision_number'],'target_url'=>'?action=documents','viewport'=>['width'=>1200,'height'=>800,'scroll_x'=>0,'scroll_y'=>0],'sensitive_content_reviewed'=>true,'image_base64'=>base64_encode(db_test_png(1200,800))];$snapshotSaved=portal_feedback_save_page_snapshot($db,$user,$snapshotPayload);db_ok(count($snapshotSaved['batch']['snapshots'])===1&&!array_key_exists('image_bytes',$snapshotSaved['batch']['snapshots'][0])&&(int)$snapshotSaved['batch']['snapshots'][0]['sensitive_content_reviewed']===1&&$snapshotSaved['batch']['snapshots'][0]['redaction_profile']==='password-explicit-v1','immutable snapshot metadata must read back without embedding private image bytes');$idempotent=portal_feedback_save_page_snapshot($db,$user,$snapshotPayload);db_ok($idempotent['already_exists']===true,'an exact immutable binding retry must be idempotent');try{portal_feedback_save_page_snapshot($db,$user,array_replace($snapshotPayload,['viewport'=>['width'=>1200,'height'=>800,'scroll_x'=>0,'scroll_y'=>1]]));db_fail('same image with different scroll binding accepted as idempotent');}catch(PortalFeedbackHttpException $e){db_ok($e->statusCode===409,'different immutable metadata binding must conflict even when image bytes match');}$batchKey=$db->prepare('SELECT batch_id FROM dbo.site_feedback_batches WHERE public_id=CONVERT(uniqueidentifier,?)');$batchKey->execute([$batch['public_id']]);db_ok(portal_feedback_missing_before_targets($db,(int)$batchKey->fetchColumn(),(int)$reopened['batch']['revision_number'])===[],'exact-revision before snapshot must cover the batch target');
 try{portal_feedback_save_page_snapshot($db,$user,array_replace($snapshotPayload,['image_base64'=>base64_encode(db_test_png(1200,800,0))]));db_fail('immutable snapshot overwrite accepted');}catch(PortalFeedbackHttpException $e){db_ok($e->statusCode===409,'different bytes must not overwrite an immutable snapshot');}
 $nonAdmin=$user;$nonAdmin['role_code']='reader';try{portal_feedback_complete($db,$nonAdmin,['batch_id'=>$batch['public_id'],'summary'=>'不得接受']);db_fail('non-admin completion accepted');}catch(PortalFeedbackHttpException $e){db_ok($e->statusCode===403,'only an administrator may record external completion');}
 $admin=$user;$admin['role_code']='admin';try{portal_feedback_complete($db,$admin,['batch_id'=>$batch['public_id'],'summary'=>'尚未整理規格']);db_fail('completion skipped specification analysis');}catch(PortalFeedbackHttpException $e){db_ok($e->statusCode===409,'completion must require analysis-ready status');}
 $db->prepare("UPDATE dbo.site_feedback_batches SET status_code='awaiting_approval' WHERE public_id=CONVERT(uniqueidentifier,?)")->execute([$batch['public_id']]);
 $completed=portal_feedback_complete($db,$admin,['batch_id'=>$batch['public_id'],'summary'=>'外部協作已完成並通過回歸測試']);db_ok($completed['batch']['status_code']==='completed'&&$completed['batch']['execution_summary']==='外部協作已完成並通過回歸測試'&&!empty($completed['batch']['completed_at']),'administrator must complete directly from the analysis-ready state without an approval record');
 $completionEvent=$db->prepare("SELECT COUNT(*) FROM dbo.site_feedback_events e JOIN dbo.site_feedback_batches b ON b.batch_id=e.batch_id WHERE b.public_id=CONVERT(uniqueidentifier,?) AND e.event_type='feedback_batch_completed_external'");$completionEvent->execute([$batch['public_id']]);db_ok((int)$completionEvent->fetchColumn()===1,'external completion acknowledgement must append exactly one audit event');
 try{portal_feedback_save_page_snapshot($db,$nonAdmin,array_replace($snapshotPayload,['snapshot_kind'=>'after']));db_fail('non-admin after snapshot accepted');}catch(PortalFeedbackHttpException $e){db_ok($e->statusCode===403,'only an administrator may save a completed after snapshot');}
 $afterSaved=portal_feedback_save_page_snapshot($db,$admin,array_replace($snapshotPayload,['snapshot_kind'=>'after']));db_ok(count($afterSaved['batch']['snapshots'])===2,'administrator must be able to save one exact-revision after snapshot only after completion');
 try{portal_feedback_save_page_snapshot($db,$admin,array_replace($snapshotPayload,['snapshot_kind'=>'after','target_url'=>'?action=admin']));db_fail('snapshot for a page without a batch item accepted');}catch(PortalFeedbackHttpException $e){db_ok($e->statusCode===422,'snapshot target must belong to an active batch item; got HTTP '.$e->statusCode);}
 $events=$db->prepare('SELECT COUNT(*) FROM dbo.site_feedback_events e JOIN dbo.site_feedback_batches b ON b.batch_id=e.batch_id WHERE b.public_id=CONVERT(uniqueidentifier,?)');$events->execute([$batch['public_id']]);db_ok((int)$events->fetchColumn()>=4,'append-only audit events must cover mutations');
 $immutableBlocked=false;try{$attempt=$db->prepare('UPDATE dbo.site_feedback_snapshots SET image_sha256=image_sha256 WHERE public_id=CONVERT(uniqueidentifier,?)');$attempt->execute([$snapshotSaved['snapshot_id']]);}catch(PDOException $e){$immutableBlocked=true;}db_ok($immutableBlocked,'database trigger must reject UPDATE even for a broad legacy principal');
 if($db->inTransaction())$db->rollBack();echo "[OK] site feedback database create/update/soft-delete/audit integration rolled back.\n";
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
