[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'document_version_engine.ps1')
Add-Type -AssemblyName System.Drawing
function Write-Png([string]$Path,[Drawing.Color]$Color){$b=[Drawing.Bitmap]::new(4,4);try{$b.SetPixel(0,0,$Color);$b.Save($Path,[Drawing.Imaging.ImageFormat]::Png)}finally{$b.Dispose()}}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
$root=Join-Path ([IO.Path]::GetTempPath()) ('twwater-restore-recovery-'+[Guid]::NewGuid().ToString('N'));$drive=Join-Path $root 'drive';$website=Join-Path $root 'website';$versions=Join-Path $root 'versions';$archive=Join-Path $root 'archive';$sessions=Join-Path $root 'sessions';foreach($d in @($drive,$website,$versions,$archive,$sessions)){[void][IO.Directory]::CreateDirectory($d)};$keyDir=Join-Path $archive '.keys';[void][IO.Directory]::CreateDirectory($keyDir);$keyPath=Join-Path $keyDir 'image-command.key';[IO.File]::WriteAllBytes($keyPath,[byte[]](0..31));$key=[IO.File]::ReadAllBytes($keyPath);$id=[Guid]::NewGuid().ToString();$relative='image.png';$path=Join-Path $website $relative
function Request([string]$Op,[string]$Target,[string]$Expected,[string]$RequestedUtc=''){if($RequestedUtc-eq''){$RequestedUtc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')};$r=[ordered]@{schema_version=2;operation='restore';archive_scope='image-source';operation_id=$Op;document_public_id=$id;document_relative_path=$relative;original_file_name='image.png';extension='png';target_content_hash=$Target;expected_current_hash=$Expected;requested_by_user_id=7;requested_utc=$RequestedUtc};$r.request_hmac=Get-TWWaterImageRestoreHmac -Request $r -Key $key;return $r}
try{Write-Png $path ([Drawing.Color]::Blue);$old=Hash $path;[void](Save-TWWaterArchivedVersion -SourcePath $path -VersionRoot $archive -DocumentPublicId $id -RelativePath $relative -Reason publish -ActorReference test);Write-Png $path ([Drawing.Color]::Red);$current=Hash $path;$processing=Join-Path $sessions 'document-version-requests/processing';[void][IO.Directory]::CreateDirectory($processing)
 $op1=[Guid]::NewGuid().ToString();$p1=Join-Path $processing ($op1+'.json');[IO.File]::WriteAllText($p1,((Request $op1 $old $current)|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));(Get-Item $p1).LastWriteTimeUtc=[DateTime]::UtcNow.AddMinutes(-1);$count=Invoke-TWWaterDocumentVersionRequests -SourceRoot $drive -VersionRoot $versions -ImageSourceRoot $website -ImageArchiveRoot $archive -ImageCommandKeyPath $keyPath -SessionRoot $sessions;Assert ($count-eq1) 'Stale processing request was not reclaimed.';Assert ((Hash $path)-eq$old) 'Reclaimed restore did not reach target.';Assert (Test-Path -LiteralPath (Join-Path $sessions ('document-version-requests/completed/'+$op1+'.json'))) 'Reclaimed restore completion evidence missing.'
 Write-Png $path ([Drawing.Color]::Red);Assert ((Hash $path)-eq$current) 'Recovery fixture reset failed.';[void](Save-TWWaterArchivedVersion -SourcePath $path -VersionRoot $archive -DocumentPublicId $id -RelativePath $relative -Reason restore -ActorReference test);Write-Png $path ([Drawing.Color]::Blue);$op2=[Guid]::NewGuid().ToString();$p2=Join-Path $processing ($op2+'.json');[IO.File]::WriteAllText($p2,((Request $op2 $old $current ([DateTime]::UtcNow.AddMinutes(-30).ToString('yyyy-MM-ddTHH:mm:ssZ')))|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));(Get-Item $p2).LastWriteTimeUtc=[DateTime]::UtcNow.AddMinutes(-1);$count=Invoke-TWWaterDocumentVersionRequests -SourceRoot $drive -VersionRoot $versions -ImageSourceRoot $website -ImageArchiveRoot $archive -ImageCommandKeyPath $keyPath -SessionRoot $sessions;Assert ($count-eq1) 'Post-mutation crash was not reconciled.';$done=Get-Content -LiteralPath (Join-Path $sessions ('document-version-requests/completed/'+$op2+'.json')) -Raw|ConvertFrom-Json;Assert ([bool]$done.recovered) 'Recovered completion is not marked recovered.';Assert ((Hash $path)-eq$old) 'Post-mutation recovery rewrote target unexpectedly.';Write-Host '[OK] Stale restore claims are reclaimed and post-mutation completion is reconciled.'}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
