<?php
declare(strict_types=1);
function analysis_lock_assert(bool $condition,string $message):void{if(!$condition){fwrite(STDERR,"[FAIL] {$message}\n");exit(1);}}
$root=dirname(__DIR__);$js=(string)file_get_contents($root.'/assets/site-feedback.js');$css=(string)file_get_contents($root.'/assets/site-feedback.css');
analysis_lock_assert(str_contains($js,"var ANALYSIS_STATUSES = ['queued_analysis', 'analyzing']"),'queued and analyzing must share one persistent analysis-lock predicate');
analysis_lock_assert(str_contains($js,'FeedbackWorkspace.prototype.isAnalysisBusy'),'workspace must derive persistent analysis lock from server batch status');
analysis_lock_assert(str_contains($js,"className:'site-feedback-analysis-busy'")&&str_contains($js,"role:'status'")&&str_contains($js,"'aria-live':'polite'")&&str_contains($js,'site-feedback-spinner'),'right panel must expose an accessible persistent waiting notice and spinner');
analysis_lock_assert(str_contains($js,"text:'正在整理精確規格…'")&&str_contains($js,"submitButton.textContent='整理精確規格'")&&str_contains($js,"className:'site-feedback-spinner is-button'")&&str_contains($js,'disabled:Boolean(this.saveBusy||this.workflowBusy||analysisBusy||this.items.length===0)'),'submit button must remain visibly disabled with a spinner for the entire server-side analysis state');
analysis_lock_assert(str_contains($js,"this.nodes.workspace.setAttribute('aria-busy',analysisBusy?'true':'false')")&&str_contains($js,'this.nodes.analysisBusyNotice.hidden=!analysisBusy'),'workspace aria-busy and visible waiting notice must follow server state');
analysis_lock_assert(str_contains($js,'locked=this.saveBusy||this.workflowBusy||analysisBusy')&&str_contains($js,'this.nodes.frame.inert=locked')&&str_contains($js,'this.nodes.overlay.style.pointerEvents=locked'),'page selector, tools, live frame, and annotation overlay must stay locked during analysis');
analysis_lock_assert(str_contains($js,'this.nodes.createTrigger.disabled=analysisBusy')&&str_contains($js,'this.nodes.historyTrigger.disabled=analysisBusy'),'new-batch and history context switches must remain locked during analysis');
analysis_lock_assert(str_contains($js,"if(self.isAnalysisBusy()&&['save','submit','complete','capture-snapshot','open-start','archive-batch','restore-batch'].includes(action||''))return;")&&str_contains($js,'if(self.isAnalysisBusy())return;if(!self.nodes.batchDialog.open)'),'event handlers must reject synthetic mutation and history-switch clicks while analysis is active');
analysis_lock_assert(str_contains($js,"FeedbackWorkspace.prototype.setTool = function (tool) {\n    if(this.isAnalysisBusy())return;")&&str_contains($js,"FeedbackWorkspace.prototype.loadTarget = function (url) {\n    url = String(url || '?action=documents');\n    if(this.isAnalysisBusy()&&((this.nodes.frame.dataset.targetUrl&&this.nodes.frame.dataset.targetUrl!==url)")&&str_contains($js,"FeedbackWorkspace.prototype.captureCurrentSnapshot = async function(kind){\n    if(this.isAnalysisBusy())return;")&&str_contains($js,"FeedbackWorkspace.prototype.saveAll = function () {\n    if(this.isAnalysisBusy())return Promise.resolve(false);"),'context and mutation methods must fail closed when invoked directly during analysis');
analysis_lock_assert(str_contains($js,'this.pollTimer = null')&&str_contains($js,'this.pollInFlight = false')&&str_contains($js,'this.pollGeneration = 0'),'poll lifecycle must track both scheduled and in-flight work with an opaque generation');
analysis_lock_assert(str_contains($js,'var batchId=String(this.batch.public_id)')&&str_contains($js,'var revision=Number(this.batch.revision_number)')&&str_contains($js,'var generation=++this.pollGeneration'),'poll must capture batch, revision, and generation before awaiting');
analysis_lock_assert(str_contains($js,'if(generation!==self.pollGeneration||String(self.batch?.public_id||\'\')!==batchId||Number(self.batch?.revision_number)!==revision)return;'),'stale poll responses must not replace another batch or revision');
analysis_lock_assert(str_contains($js,'if(this.pollTimer!==null||this.pollInFlight)return;')&&str_contains($js,'self.pollInFlight=true;')&&str_contains($js,'self.pollInFlight=false;'),'repeated pollIfNeeded calls must not create a second request while the first status POST is in flight');
analysis_lock_assert(str_contains($js,'clearTimeout(this.pollTimer)')&&str_contains($js,'this.pollTimer=setTimeout'),'polling must retire the previous timer before scheduling exactly one successor');
analysis_lock_assert(str_contains($js,"'精確規格整理完成，可以複製或下載。'")&&str_contains($js,"'精確規格整理失敗，可修正內容後重新整理。'"),'completion and failure must clearly announce unlock outcomes');
analysis_lock_assert(str_contains($css,'.site-feedback-analysis-busy{')&&str_contains($css,'@keyframes site-feedback-spinner')&&str_contains($css,'prefers-reduced-motion:reduce'),'waiting notice, spinner, and reduced-motion fallback must be styled');
echo "[OK] persistent AI specification-analysis lock and generation-safe polling contracts passed.\n";
