[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'image_source_version_engine.ps1')
Add-Type -AssemblyName System.Drawing
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
$root=Join-Path ([IO.Path]::GetTempPath()) ('twwater-signed-image-'+[Guid]::NewGuid().ToString('N'));$source=Join-Path $root 'source';$preview=Join-Path $root 'preview';$archive=Join-Path $root 'archive';$sessions=Join-Path $root 'sessions';foreach($d in @($source,$preview,$archive,$sessions)){[void][IO.Directory]::CreateDirectory($d)};$keys=Join-Path $archive '.keys';[void][IO.Directory]::CreateDirectory($keys);$keyPath=Join-Path $keys 'image-command.key';[IO.File]::WriteAllBytes($keyPath,[byte[]](0..31))
$id=[Guid]::NewGuid().ToString();$doc=Join-Path $preview $id;[void][IO.Directory]::CreateDirectory($doc);$relative='image.png';$sourcePath=Join-Path $source $relative;$candidate=Join-Path $doc 'candidate.png';$wrongFormat=Join-Path $doc 'wrong-format.png';$a=[Drawing.Bitmap]::new(8,8);try{$a.SetPixel(0,0,[Drawing.Color]::Black);$a.Save($sourcePath,[Drawing.Imaging.ImageFormat]::Png)}finally{$a.Dispose()};$b=[Drawing.Bitmap]::new($sourcePath);try{$b.SetPixel(2,2,[Drawing.Color]::Red);$b.Save($candidate,[Drawing.Imaging.ImageFormat]::Png);$b.Save($wrongFormat,[Drawing.Imaging.ImageFormat]::Jpeg)}finally{$b.Dispose()};$old=Hash $sourcePath;$new=Hash $candidate;$binding=[ordered]@{binding_id=[Guid]::NewGuid().ToString();issued_utc=[DateTime]::UtcNow.AddMinutes(-1).ToString('yyyy-MM-ddTHH:mm:ssZ');expires_utc=[DateTime]::UtcNow.AddHours(1).ToString('yyyy-MM-ddTHH:mm:ssZ');public_id=$id;relative_path=$relative;source_hash=$old;extension='png';source_width=8;source_height=8;regions='2,2,3,3'};$binding.binding_hmac=Get-TWWaterImageBindingHmac -Binding $binding -Key ([IO.File]::ReadAllBytes($keyPath));$manifest=[ordered]@{schema_version=2;document_id=$id;relative_path=$relative;source_path=$sourcePath;source_sha256=$old;candidate_path=$candidate;candidate_sha256=$new;source_size=@(8,8);roi_px=@(2,2,3,3);outside_roi_changed_pixels=[int64]0;validation_status='passed';external_api_used=$false;source_overwritten=$false;binding=$binding};$manifestPath=Join-Path $doc 'manifest.json'
try{
 $bad=[ordered]@{};foreach($entry in $manifest.GetEnumerator()){$bad[$entry.Key]=$entry.Value};$badBinding=[ordered]@{};foreach($entry in $binding.GetEnumerator()){$badBinding[$entry.Key]=$entry.Value};$badBinding.binding_hmac='0'*64;$bad.binding=$badBinding;[IO.File]::WriteAllText($manifestPath,($bad|ConvertTo-Json -Depth 8),(New-Object Text.UTF8Encoding($false)));$actual='';try{[void](Publish-TWWaterImageOutputFromManifest -ManifestPath $manifestPath -SourceRoot $source -PreviewRoot $preview -ArchiveRoot $archive -SessionRoot $sessions -CommandKeyPath $keyPath)}catch{$actual=$_.Exception.Message};Assert ($actual-eq'IMAGE_BINDING_INVALID') ("Bad binding expected IMAGE_BINDING_INVALID, got $actual");Assert ((Hash $sourcePath)-eq$old) 'Bad binding changed source.'
 $expired=[ordered]@{};foreach($entry in $manifest.GetEnumerator()){$expired[$entry.Key]=$entry.Value};$expiredBinding=[ordered]@{};foreach($entry in $binding.GetEnumerator()){$expiredBinding[$entry.Key]=$entry.Value};$expiredBinding.issued_utc=[DateTime]::UtcNow.AddHours(-2).ToString('yyyy-MM-ddTHH:mm:ssZ');$expiredBinding.expires_utc=[DateTime]::UtcNow.AddHours(-1).ToString('yyyy-MM-ddTHH:mm:ssZ');$expiredBinding.Remove('binding_hmac');$expiredBinding.binding_hmac=Get-TWWaterImageBindingHmac -Binding $expiredBinding -Key ([IO.File]::ReadAllBytes($keyPath));$expired.binding=$expiredBinding;[IO.File]::WriteAllText($manifestPath,($expired|ConvertTo-Json -Depth 8),(New-Object Text.UTF8Encoding($false)));$actual='';try{[void](Publish-TWWaterImageOutputFromManifest -ManifestPath $manifestPath -SourceRoot $source -PreviewRoot $preview -ArchiveRoot $archive -SessionRoot $sessions -CommandKeyPath $keyPath)}catch{$actual=$_.Exception.Message};Assert ($actual-eq'IMAGE_BINDING_EXPIRED') ("Expired binding expected IMAGE_BINDING_EXPIRED, got $actual");Assert ((Hash $sourcePath)-eq$old) 'Expired binding changed source.'
 $extra=[ordered]@{};foreach($entry in $manifest.GetEnumerator()){$extra[$entry.Key]=$entry.Value};$extraBinding=[ordered]@{};foreach($entry in $binding.GetEnumerator()){$extraBinding[$entry.Key]=$entry.Value};$extraBinding['injected']='x';$extra.binding=$extraBinding;[IO.File]::WriteAllText($manifestPath,($extra|ConvertTo-Json -Depth 8),(New-Object Text.UTF8Encoding($false)));$actual='';try{[void](Publish-TWWaterImageOutputFromManifest -ManifestPath $manifestPath -SourceRoot $source -PreviewRoot $preview -ArchiveRoot $archive -SessionRoot $sessions -CommandKeyPath $keyPath)}catch{$actual=$_.Exception.Message};Assert ($actual-eq'IMAGE_BINDING_INVALID') ("Extra binding field expected IMAGE_BINDING_INVALID, got $actual");Assert ((Hash $sourcePath)-eq$old) 'Extra binding field changed source.'
 $disguised=[ordered]@{};foreach($entry in $manifest.GetEnumerator()){$disguised[$entry.Key]=$entry.Value};$disguised.candidate_path=$wrongFormat;$disguised.candidate_sha256=Hash $wrongFormat;[IO.File]::WriteAllText($manifestPath,($disguised|ConvertTo-Json -Depth 8),(New-Object Text.UTF8Encoding($false)));$actual='';try{[void](Publish-TWWaterImageOutputFromManifest -ManifestPath $manifestPath -SourceRoot $source -PreviewRoot $preview -ArchiveRoot $archive -SessionRoot $sessions -CommandKeyPath $keyPath)}catch{$actual=$_.Exception.Message};Assert ($actual-eq'IMAGE_FORMAT_MISMATCH') ("Disguised JPEG expected IMAGE_FORMAT_MISMATCH, got $actual");Assert ((Hash $sourcePath)-eq$old) 'Disguised image changed source.'
 [IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 8),(New-Object Text.UTF8Encoding($false)));$result=Publish-TWWaterImageOutputFromManifest -ManifestPath $manifestPath -SourceRoot $source -PreviewRoot $preview -ArchiveRoot $archive -SessionRoot $sessions -CommandKeyPath $keyPath;Assert ((Hash $sourcePath)-eq$new) 'Signed image publish did not replace source.';Assert ((Hash $result.ArchivedArtifactPath)-eq$old) 'Signed image publish did not archive original.';$snapshotPath=Join-Path (Join-Path (Join-Path $archive $id.ToLowerInvariant()) 'candidates') ($result.OperationId+'.png');Assert (Test-Path -LiteralPath $snapshotPath -PathType Leaf) 'Immutable candidate snapshot missing.';Assert ((Hash $snapshotPath)-eq$new) 'Immutable candidate snapshot hash mismatch.';$commitPath=Join-Path (Join-Path (Join-Path $archive $id.ToLowerInvariant()) 'commits') ($result.OperationId+'.json');$commit=Get-Content -LiteralPath $commitPath -Raw|ConvertFrom-Json;Assert ([string]$commit.operation-eq'publish'-and[string]$commit.status-eq'local-published') 'Publish commit status must be local-published.';$bindingMarker=Join-Path (Join-Path (Join-Path $archive $id.ToLowerInvariant()) 'bindings') ($binding.binding_id+'.json');Assert (Test-Path -LiteralPath $bindingMarker -PathType Leaf) 'Consumed binding marker missing.';[IO.File]::Copy($result.ArchivedArtifactPath,$sourcePath,$true);Assert ((Hash $sourcePath)-eq$old) 'Replay fixture failed to restore original source.';$actual='';try{[void](Publish-TWWaterImageOutputFromManifest -ManifestPath $manifestPath -SourceRoot $source -PreviewRoot $preview -ArchiveRoot $archive -SessionRoot $sessions -CommandKeyPath $keyPath)}catch{$actual=$_.Exception.Message};Assert ($actual-eq'IMAGE_BINDING_REPLAYED') ("Replayed binding expected IMAGE_BINDING_REPLAYED, got $actual");Assert ((Hash $sourcePath)-eq$old) 'Replayed binding changed source.';Assert (@(Get-ChildItem -LiteralPath (Split-Path -Parent $snapshotPath) -File).Count-eq1) 'Replayed binding created an orphan candidate snapshot.'
 Write-Host '[OK] Signed image binding authorizes only its catalog path/hash/ROI.'
}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
