<?php
declare(strict_types=1);
function version_blob_assert(bool $condition,string $message):void{if(!$condition){fwrite(STDERR,"[FAIL] {$message}\n");exit(1);}}
$root=dirname(__DIR__);$migration=$root.'/database/025_document_version_contents.sql';version_blob_assert(is_file($migration),'migration 025 is missing');$sql=(string)file_get_contents($migration);
foreach(['CREATE TABLE dbo.document_version_contents','content_bytes VARBINARY(MAX)','157286400','DATALENGTH(content_bytes)','HASHBYTES(\'SHA2_256\'','current_version_id BIGINT','version_capture_status VARCHAR(8)','version_capture_error_code VARCHAR(64)','FK_documents_current_version','CREATE OR ALTER PROCEDURE dbo.portal_prepare_document_version_capture','CREATE OR ALTER PROCEDURE dbo.portal_capture_current_document_version','CREATE OR ALTER PROCEDURE dbo.portal_mark_document_version_capture_failed','CREATE OR ALTER PROCEDURE dbo.portal_list_document_versions','CREATE OR ALTER PROCEDURE dbo.portal_read_document_version_content','CREATE OR ALTER PROCEDURE dbo.portal_verify_document_version_contents','LEFT JOIN dbo.document_versions v ON v.version_id=i.version_id','WITH(UPDLOCK,HOLDLOCK)','DENY SELECT,INSERT,UPDATE,DELETE ON dbo.document_version_contents','DENY INSERT ON dbo.document_versions','025_document_version_contents.sql'] as $needle){version_blob_assert(str_contains($sql,$needle),'migration contract missing: '.$needle);}
version_blob_assert(preg_match('/CREATE OR ALTER PROCEDURE dbo\.portal_capture_current_document_version\s+@document_id BIGINT,@expected_hash CHAR\(64\),@content_bytes VARBINARY\(MAX\)\s+AS/s',$sql)===1,'capture procedure signature must not accept caller-controlled attribution');version_blob_assert(!str_contains($sql,'UPDATE dbo.document_versions'),'migration must not rewrite immutable version history');
$rollbackSql=(string)file_get_contents($root.'/database/025_document_version_contents_rollback.sql');foreach(['Refusing rollback','immutable document version bytes already exist','DROP PROCEDURE dbo.portal_capture_current_document_version','DROP TABLE dbo.document_version_contents',"DELETE FROM dbo.schema_migrations WHERE script_name=N'025_document_version_contents.sql'"] as $needle){version_blob_assert(str_contains($rollbackSql,$needle),'rollback contract missing: '.$needle);}version_blob_assert(!preg_match('/\bRETURN\b/i',$rollbackSql),'rollback must not rely on batch-local RETURN');
$runtime=(string)file_get_contents($root.'/app/document_versions.php');foreach(['function portal_capture_current_document_version_content','sqlsrv_send_stream_data','SendStreamParamsAtExec','function portal_get_database_document_versions','function portal_stream_database_document_version','portal_prepare_document_version_capture','portal_mark_document_version_capture_failed'] as $needle){version_blob_assert(str_contains($runtime,$needle),'runtime contract missing: '.$needle);}
$bootstrap=(string)file_get_contents($root.'/app/bootstrap.php');version_blob_assert(str_contains($bootstrap,'portal_capture_current_document_version_contents'),'document sync must capture current version bytes');version_blob_assert(str_contains($bootstrap,"version_failed') > 0" )||str_contains($bootstrap,"version_failed'] ?? 0"),'bridge must gate capture failures');$presentation=(string)file_get_contents($root.'/app/presentation.php');version_blob_assert(substr_count($presentation,'portal_document_version_blob_schema_ready')>=2,'presentation and Markdown flows must not bypass SQL-backed version capture');$index=(string)file_get_contents($root.'/index.php');version_blob_assert(str_contains($index,'文件ID:錯誤碼')&&str_contains($index,"['error_code']"),'admin sync must display document IDs with durable capture error codes');foreach(['UQ_document_versions_document_hash','FK_document_version_contents_version','FK_documents_current_version','CK_document_version_contents_size','TR_document_version_contents_immutable','DATABASE_PRINCIPAL_ID(N\'TWWATER_PORTAL_APP\')'] as $needle){version_blob_assert(str_contains($runtime,$needle),'exact runtime readiness contract missing: '.$needle);}
echo "[OK] immutable SQL version bytes, durable capture state, procedure-only access, rollback, streaming, and sync contracts passed.\n";
