[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'document_version_engine.ps1')
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Assert([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
$root=Join-Path ([IO.Path]::GetTempPath()) ('twwater-schema1-image-'+[Guid]::NewGuid().ToString('N'));$source=Join-Path $root 'source';$versions=Join-Path $root 'versions';$sessions=Join-Path $root 'sessions';foreach($d in @($source,$versions,$sessions)){[void][IO.Directory]::CreateDirectory($d)}
$id=[Guid]::NewGuid().ToString();$relative='image.png';$path=Join-Path $source $relative
try{[IO.File]::WriteAllText($path,'old-image');$old=Hash $path;[void](Save-TWWaterArchivedVersion -SourcePath $path -VersionRoot $versions -DocumentPublicId $id -RelativePath $relative -Reason publish -ActorReference test);[IO.File]::WriteAllText($path,'current-image');$current=Hash $path;$pending=Join-Path $sessions 'document-version-requests/pending';[void][IO.Directory]::CreateDirectory($pending);$op=[Guid]::NewGuid().ToString();$request=[ordered]@{schema_version=1;operation='restore';archive_scope='document';operation_id=$op;document_public_id=$id;document_relative_path=$relative;original_file_name='image.png';extension='png';target_content_hash=$old;expected_current_hash=$current;requested_by_user_id=7;requested_utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')};[IO.File]::WriteAllText((Join-Path $pending ($op+'.json')),($request|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$processed=Invoke-TWWaterDocumentVersionRequests -SourceRoot $source -VersionRoot $versions -SessionRoot $sessions;Assert ($processed-eq0) 'Unsigned schema-1 image restore was processed.';Assert ((Hash $path)-eq$current) 'Unsigned schema-1 image restore mutated source.';$failed=Get-Content -LiteralPath (Join-Path $sessions ('document-version-requests/failed/'+$op+'.json')) -Raw|ConvertFrom-Json;Assert ([string]$failed.error_code-eq'IMAGE_ASSET_REQUIRES_SIGNED_IMAGE_PIPELINE') 'Schema-1 image restore did not fail with signed-pipeline error.';Write-Host '[OK] Schema-1 restore rejects image assets before mutation.'}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
