<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
function m025_assert(bool $c,string $m):void{if(!$c)throw new RuntimeException($m);}
function m025_mark(string $step):void{$path=dirname(__DIR__).'/.hermes/evidence/m025-progress.log';if($step==='start'&&is_file($path))unlink($path);file_put_contents($path,$step."\n",FILE_APPEND|LOCK_EX);}
function m025_batches(PDO $db,string $sql):void{$sql=preg_replace('/^\s*SET\s+XACT_ABORT\s+ON\s*;?\s*$/mi','',$sql)??$sql;$sql=preg_replace('/^\s*(BEGIN|COMMIT)\s+TRANSACTION\s*;?\s*$/mi','',$sql)??$sql;foreach(preg_split('/^\s*GO\s*$/mi',$sql)?:[] as $batch){if(trim($batch)!=='')$db->exec($batch);}}
function m025_fixture(PDO $db,string $s,string $r,string $hash,int $size):void{$db->exec("CREATE SCHEMA [$s]");$db->exec("CREATE ROLE [$r]");$db->exec("CREATE TABLE [$s].schema_migrations(migration_id INT IDENTITY PRIMARY KEY,script_name NVARCHAR(255) NOT NULL UNIQUE,applied_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),applied_by NVARCHAR(256) NOT NULL DEFAULT SUSER_SNAME(),checksum_sha256 CHAR(64) NULL)");$db->exec("CREATE TABLE [$s].documents(document_id BIGINT NOT NULL PRIMARY KEY,relative_path NVARCHAR(512) NOT NULL,file_size_bytes BIGINT NOT NULL,source_modified_at DATETIME2(3) NOT NULL,content_hash CHAR(64) NULL,status_code VARCHAR(16) NOT NULL)");$db->exec("CREATE TABLE [$s].document_versions(version_id BIGINT IDENTITY NOT NULL PRIMARY KEY,public_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),document_id BIGINT NOT NULL,version_number INT NOT NULL,source_content_hash CHAR(64) NOT NULL,source_file_size_bytes BIGINT NOT NULL,source_modified_at DATETIME2(3) NOT NULL,source_relative_path NVARCHAR(512) NOT NULL,created_by_user_id BIGINT NULL,created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),rowver ROWVERSION NOT NULL,CONSTRAINT UQ_document_versions_public_id UNIQUE(public_id),CONSTRAINT UQ_document_versions_document_number UNIQUE(document_id,version_number),CONSTRAINT UQ_document_versions_document_hash UNIQUE(document_id,source_content_hash),CONSTRAINT UQ_document_versions_version_document UNIQUE(version_id,document_id),CONSTRAINT FK_document_versions_document FOREIGN KEY(document_id) REFERENCES [$s].documents(document_id))");$q=$db->prepare("INSERT [$s].documents(document_id,relative_path,file_size_bytes,source_modified_at,content_hash,status_code) VALUES(1,N'文件/測試.bin',?,'2026-08-31T00:00:00',?,'published')");$q->execute([$size,$hash]);}
function m025_rewrite(string $sql,string $s,string $r):string{return str_replace(['dbo.','TWWATER_PORTAL_APP'],['['.$s.'].',$r],$sql);}
function m025_apply(PDO $db,string $sql,string $s,string $r):void{m025_batches($db,m025_rewrite($sql,$s,$r));}
function m025_capture_stream(PDO $db,string $s,string $hash,$stream,int $id=1):array{$q=$db->prepare("EXEC [$s].portal_capture_current_document_version @document_id=?,@expected_hash=?,@content_bytes=?");$q->bindParam(1,$id,PDO::PARAM_INT);$q->bindParam(2,$hash,PDO::PARAM_STR);$q->bindParam(3,$stream,PDO::PARAM_LOB,0,PDO::SQLSRV_ENCODING_BINARY);$q->execute();$row=$q->fetch();while($q->nextRowset()){}return is_array($row)?$row:[];}
function m025_capture(PDO $db,string $s,string $hash,string $content,int $id=1):array{$stream=fopen('php://temp','w+b');fwrite($stream,$content);rewind($stream);try{return m025_capture_stream($db,$s,$hash,$stream,$id);}finally{fclose($stream);}}
$db=portal_open_database(portal_config(false));$name=(string)$db->query('SELECT DB_NAME()')->fetchColumn();m025_assert($name!==''&&!in_array(strtolower($name),['master','model','msdb','tempdb'],true),'Refusing system database');$migration=(string)file_get_contents(dirname(__DIR__).'/database/025_document_version_contents.sql');$migration026=(string)file_get_contents(dirname(__DIR__).'/database/026_document_version_historical_content.sql');$migration027=(string)file_get_contents(dirname(__DIR__).'/database/027_document_version_complete_verification.sql');$migration028=(string)file_get_contents(dirname(__DIR__).'/database/028_document_version_500mib_limit.sql');$rollback=(string)file_get_contents(dirname(__DIR__).'/database/025_document_version_contents_rollback.sql');$suffix=substr(bin2hex(random_bytes(8)),0,12);$s='m025_'.$suffix;$r='r_'.$s;$content="binary\0fixture\xFF";$hash=hash('sha256',$content);
m025_mark('start');$db->beginTransaction();try{m025_fixture($db,$s,$r,$hash,strlen($content));$principal=$db->query("SELECT name,type_desc,is_fixed_role FROM sys.database_principals WHERE principal_id=DATABASE_PRINCIPAL_ID('$r')")->fetch();m025_mark('fixture-principal-'.json_encode($principal));m025_apply($db,$migration,$s,$r);m025_mark('migration1-role-'.(int)$db->query("SELECT ISNULL(DATABASE_PRINCIPAL_ID('$r'),0)")->fetchColumn());m025_apply($db,$migration,$s,$r);m025_mark('migration2-role-'.(int)$db->query("SELECT ISNULL(DATABASE_PRINCIPAL_ID('$r'),0)")->fetchColumn());$db->exec("EXEC [$s].portal_prepare_document_version_capture");$result=m025_capture($db,$s,$hash,$content);m025_assert((int)($result['version_id']??0)>0,'Capture did not return version');m025_capture($db,$s,$hash,$content);m025_mark('capture');
 $lobQuery=$db->prepare("EXEC [$s].portal_read_document_version_content @document_id=?,@content_hash=?");$id=1;$lobQuery->execute([$id,$hash]);$size=$stored=$actual=$lob=null;$lobQuery->bindColumn(1,$size,PDO::PARAM_INT);$lobQuery->bindColumn(2,$stored,PDO::PARAM_STR);$lobQuery->bindColumn(3,$actual,PDO::PARAM_STR);$lobQuery->bindColumn(4,$lob,PDO::PARAM_LOB,0,PDO::SQLSRV_ENCODING_BINARY);m025_assert($lobQuery->fetch(PDO::FETCH_BOUND)===true&&is_resource($lob),'Read proc must return a LOB stream');m025_assert(stream_get_contents($lob)===$content&&hash_equals($hash,(string)$actual),'LOB read mismatch');fclose($lob);while($lobQuery->nextRowset()){}m025_mark('lob-read');
 $row=$db->query("SELECT d.current_version_id,d.version_capture_status,v.version_number,c.file_size_bytes,LOWER(CONVERT(CHAR(64),HASHBYTES('SHA2_256',c.content_bytes),2)) actual_hash,(SELECT COUNT(*) FROM [$s].document_versions) version_count,(SELECT COUNT(*) FROM [$s].document_version_contents) content_count FROM [$s].documents d JOIN [$s].document_versions v ON v.version_id=d.current_version_id JOIN [$s].document_version_contents c ON c.version_id=v.version_id WHERE d.document_id=1")->fetch();m025_assert(is_array($row)&&$row['version_capture_status']==='ready'&&(int)$row['version_number']===1&&(int)$row['file_size_bytes']===strlen($content)&&hash_equals($hash,(string)$row['actual_hash'])&&(int)$row['version_count']===1&&(int)$row['content_count']===1,'Capture/replay invariant failed');m025_mark('row-verify');
 $roleId=(int)$db->query("SELECT DATABASE_PRINCIPAL_ID('$r')")->fetchColumn();$contentId=(int)$db->query("SELECT OBJECT_ID('[$s].document_version_contents')")->fetchColumn();$versionsId=(int)$db->query("SELECT OBJECT_ID('[$s].document_versions')")->fetchColumn();$perms=$db->query("SELECT permission_name,state_desc,major_id FROM sys.database_permissions WHERE grantee_principal_id=$roleId")->fetchAll();$contentPerm=[];$execCount=0;$versionInsert='';foreach($perms as $p){if((int)$p['major_id']===$contentId)$contentPerm[$p['permission_name']]=$p['state_desc'];if($p['permission_name']==='EXECUTE'&&$p['state_desc']==='GRANT')$execCount++;if((int)$p['major_id']===$versionsId&&$p['permission_name']==='INSERT')$versionInsert=$p['state_desc'];}foreach(['SELECT','INSERT','UPDATE','DELETE'] as $p)m025_assert(($contentPerm[$p]??'')==='DENY',"$p content permission must be DENY");m025_assert($execCount>=6&&$versionInsert==='DENY','Procedure grants or metadata INSERT deny missing');m025_mark('permissions');
 $bad=false;try{m025_capture($db,$s,$hash,$content.'bad');}catch(Throwable){$bad=true;}$tx=$db->query('SELECT @@TRANCOUNT tran_count,XACT_STATE() xact_state')->fetch();m025_assert($bad&&(int)$tx['tran_count']>0&&(int)$tx['xact_state']===1,'Mismatched bytes must preserve a committable caller transaction');m025_mark('bad-capture');$overHash=hash('sha256',"\0");$over=$db->prepare("INSERT [$s].documents(document_id,relative_path,file_size_bytes,source_modified_at,content_hash,status_code,current_version_id,version_capture_status,version_capture_error_code,version_capture_updated_at) VALUES(2,N'over-limit.bin',157286401,'2026-08-31',?,'published',NULL,'pending',NULL,SYSUTCDATETIME())");$over->execute([$overHash]);$overRejected=false;try{m025_capture($db,$s,$overHash,"\0",2);}catch(Throwable){$overRejected=true;}$overTx=$db->query('SELECT XACT_STATE()')->fetchColumn();m025_assert($overRejected&&(int)$overTx===1&&(int)$db->query("SELECT COUNT(*) FROM [$s].document_versions WHERE document_id=2")->fetchColumn()===0,'150 MiB + 1 byte must fail before version insertion and preserve caller transaction');m025_mark('over-limit');$blocked=false;try{$db->exec("UPDATE [$s].document_version_contents SET content_hash=content_hash");}catch(Throwable){$blocked=true;}m025_assert($blocked,'Immutable UPDATE was accepted');m025_mark('immutable');
}finally{if($db->inTransaction())$db->rollBack();}
$q=$db->prepare("SELECT COUNT(*) FROM sys.schemas WHERE name=?");$q->execute([$s]);m025_assert((int)$q->fetchColumn()===0,'Main fixture residue');
$s2='m025r_'.$suffix;$r2='r_'.$s2;$db->beginTransaction();try{m025_fixture($db,$s2,$r2,$hash,strlen($content));m025_apply($db,$migration,$s2,$r2);m025_apply($db,$rollback,$s2,$r2);m025_apply($db,$rollback,$s2,$r2);m025_assert($db->query("SELECT CASE WHEN OBJECT_ID('[$s2].document_version_contents') IS NULL AND COL_LENGTH('[$s2].documents','current_version_id') IS NULL THEN 1 ELSE 0 END")->fetchColumn()==1,'Rollback replay did not remove additive schema');}finally{if($db->inTransaction())$db->rollBack();}
$s3='m028b_'.$suffix;$r3='r_'.$s3;$db->beginTransaction();try{m025_fixture($db,$s3,$r3,$hash,strlen($content));foreach([$migration,$migration026] as $m)m025_apply($db,$m,$s3,$r3);$db->exec("INSERT [$s3].schema_migrations(script_name,checksum_sha256) VALUES('027_document_version_complete_verification.sql',NULL)");m025_apply($db,$migration028,$s3,$r3);$overHash=hash('sha256',"\0");$over=$db->prepare("INSERT [$s3].documents(document_id,relative_path,file_size_bytes,source_modified_at,content_hash,status_code,current_version_id,version_capture_status,version_capture_error_code,version_capture_updated_at) VALUES(2,N'over-500mib.bin',524288001,'2026-09-01',?,'published',NULL,'pending',NULL,SYSUTCDATETIME())");$over->execute([$overHash]);$rejected=false;try{m025_capture($db,$s3,$overHash,"\0",2);}catch(Throwable){$rejected=true;}$state=(int)$db->query('SELECT XACT_STATE()')->fetchColumn();m025_assert($rejected&&$state===1&&(int)$db->query("SELECT COUNT(*) FROM [$s3].document_versions WHERE document_id=2")->fetchColumn()===0,'500 MiB + 1 byte must fail before version insertion');}finally{if($db->inTransaction())$db->rollBack();}
echo "[OK] Migration replay, procedure-only LOB stream, immutable permissions, 500 MiB boundary, caller transaction, and rollback passed with zero residue.\n";
