[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'document_version_engine.ps1')
Add-Type -AssemblyName System.Drawing
function Write-Png([string]$Path,[Drawing.Color]$Color){$b=[Drawing.Bitmap]::new(4,4);try{$b.SetPixel(0,0,$Color);$b.Save($Path,[Drawing.Imaging.ImageFormat]::Png)}finally{$b.Dispose()}}
function Assert-True{param([bool]$Condition,[string]$Message)if(-not$Condition){throw $Message}}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
$root=Join-Path ([IO.Path]::GetTempPath()) ('twwater-image-restore-'+[Guid]::NewGuid().ToString('N'));$source=Join-Path $root 'source';$imageSource=Join-Path $root 'website-source';$general=Join-Path $root 'general';$images=Join-Path $root 'images';$sessions=Join-Path $root 'sessions';foreach($d in @($source,$imageSource,$general,$images,$sessions)){[void][IO.Directory]::CreateDirectory($d)};$keys=Join-Path $images '.keys';[void][IO.Directory]::CreateDirectory($keys);$keyPath=Join-Path $keys 'image-command.key';[IO.File]::WriteAllBytes($keyPath,[byte[]](0..31));$key=[IO.File]::ReadAllBytes($keyPath)
$id='4380862e-aca7-4637-872e-0222ac65d09b';$relative='infographic/image.png';$path=Join-Path $imageSource $relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));Write-Png $path ([Drawing.Color]::Blue);$oldHash=Hash $path
[void](Save-TWWaterArchivedVersion -SourcePath $path -VersionRoot $images -DocumentPublicId $id -RelativePath $relative -Reason publish -ActorReference test)
Write-Png $path ([Drawing.Color]::Red);$currentHash=Hash $path
$generalPath=Join-Path $source $relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $generalPath));[IO.File]::WriteAllText($generalPath,'drive-must-not-change');$generalHash=Hash $generalPath
$pending=Join-Path $sessions 'document-version-requests/pending';[void][IO.Directory]::CreateDirectory($pending)
function New-Request([string]$OperationId,[string]$RequestedUtc){return [ordered]@{schema_version=2;operation='restore';archive_scope='image-source';operation_id=$OperationId;document_public_id=$id;document_relative_path=$relative;original_file_name='image.png';extension='png';target_content_hash=$oldHash;expected_current_hash=$currentHash;requested_by_user_id=7;requested_utc=$RequestedUtc}}
try{
 $staleId=[Guid]::NewGuid().ToString();$stale=New-Request $staleId ([DateTime]::UtcNow.AddMinutes(-11).ToString('yyyy-MM-ddTHH:mm:ssZ'));$stale.request_hmac=Get-TWWaterImageRestoreHmac -Request $stale -Key $key;[IO.File]::WriteAllText((Join-Path $pending ($staleId+'.json')),($stale|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$processed=Invoke-TWWaterDocumentVersionRequests -SourceRoot $source -VersionRoot $general -ImageSourceRoot $imageSource -ImageArchiveRoot $images -ImageCommandKeyPath $keyPath -SessionRoot $sessions;Assert-True ($processed-eq 0) 'Expired signed restore must not be processed.';Assert-True ((Hash $path)-eq$currentHash) 'Expired restore changed website source.';$failed=Get-Content -LiteralPath (Join-Path $sessions ('document-version-requests/failed/'+$staleId+'.json')) -Raw|ConvertFrom-Json;Assert-True ([string]$failed.error_code-eq'IMAGE_REQUEST_EXPIRED') 'Expired restore did not return expiration error.'
 $now=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ');$unsignedId=[Guid]::NewGuid().ToString();$unsigned=New-Request $unsignedId $now;[IO.File]::WriteAllText((Join-Path $pending ($unsignedId+'.json')),($unsigned|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$processed=Invoke-TWWaterDocumentVersionRequests -SourceRoot $source -VersionRoot $general -ImageSourceRoot $imageSource -ImageArchiveRoot $images -ImageCommandKeyPath $keyPath -SessionRoot $sessions;Assert-True ($processed-eq 0) 'Unsigned image restore must not be processed.';Assert-True ((Hash $path)-eq$currentHash) 'Unsigned restore changed website source.';$failed=Get-Content -LiteralPath (Join-Path $sessions ('document-version-requests/failed/'+$unsignedId+'.json')) -Raw|ConvertFrom-Json;Assert-True ([string]$failed.error_code-eq'IMAGE_RESTORE_REQUEST_INVALID') 'Unsigned restore did not return strict-schema error.'
 $op=[Guid]::NewGuid().ToString();$request=New-Request $op $now;$request.request_hmac=Get-TWWaterImageRestoreHmac -Request $request -Key $key;[IO.File]::WriteAllText((Join-Path $pending ($op+'.json')),($request|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$processed=Invoke-TWWaterDocumentVersionRequests -SourceRoot $source -VersionRoot $general -ImageSourceRoot $imageSource -ImageArchiveRoot $images -ImageCommandKeyPath $keyPath -SessionRoot $sessions;Assert-True ($processed-eq 1) 'Signed image restore must process exactly once.';Assert-True ((Hash $path)-eq$oldHash) 'Signed restore did not replace website authoritative image.';Assert-True ((Hash $generalPath)-eq$generalHash) 'Image restore modified general Drive source root.';$currentArchive=Join-Path (Join-Path (Join-Path $images $id) $currentHash) 'source.png';Assert-True (Test-Path -LiteralPath $currentArchive -PathType Leaf) 'Restore did not archive current image.'
 $completedPath=Join-Path $sessions ('document-version-requests/completed/'+$op+'.json');$completedHash=Hash $completedPath;[IO.File]::WriteAllText((Join-Path $pending ($op+'.json')),($request|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($false)));$processed=Invoke-TWWaterDocumentVersionRequests -SourceRoot $source -VersionRoot $general -ImageSourceRoot $imageSource -ImageArchiveRoot $images -ImageCommandKeyPath $keyPath -SessionRoot $sessions;Assert-True ($processed-eq 0) 'Completed request replay must be idempotent.';Assert-True ((Hash $completedPath)-eq$completedHash) 'Replay changed completed evidence.';Assert-True (-not(Test-Path -LiteralPath (Join-Path $sessions ('document-version-requests/failed/'+$op+'.json')))) 'Replay created contradictory failed evidence.';Assert-True ((Hash $path)-eq$oldHash) 'Replay changed restored source.'
 Write-Host '[OK] Image restore rejects unsigned requests and processes signed website-only requests.'
}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
