[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'document_version_engine.ps1')
Add-Type -AssemblyName System.Drawing
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Png([string]$Path,[Drawing.Color]$Color){$b=[Drawing.Bitmap]::new(4,4);try{$b.SetPixel(0,0,$Color);$b.Save($Path,[Drawing.Imaging.ImageFormat]::Png)}finally{$b.Dispose()}}
function Assert([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
$root=Join-Path ([IO.Path]::GetTempPath()) ('twwater-publish-recovery-'+[Guid]::NewGuid().ToString('N'));$source=Join-Path $root 'source';$archive=Join-Path $root 'archive';$session=Join-Path $root 'session';foreach($d in @($source,$archive,$session)){[void][IO.Directory]::CreateDirectory($d)};$id=[Guid]::NewGuid().ToString();$op=[Guid]::NewGuid().ToString();$binding=[Guid]::NewGuid().ToString();$sourcePath=Join-Path $source 'image.png';Png $sourcePath ([Drawing.Color]::Blue);$old=Hash $sourcePath;$doc=Join-Path $archive $id;$candidateRoot=Join-Path $doc 'candidates';$bindingRoot=Join-Path $doc 'bindings';$commitRoot=Join-Path $doc 'commits';foreach($d in @($candidateRoot,$bindingRoot,$commitRoot)){[void][IO.Directory]::CreateDirectory($d)};$candidate=Join-Path $candidateRoot ($op+'.png');Png $candidate ([Drawing.Color]::Red);$new=Hash $candidate;$commit=Join-Path $commitRoot ($op+'.json')
try{$actual='';try{[void](Publish-TWWaterDocumentVersion -SourceRoot $source -VersionRoot $archive -SessionRoot $session -DocumentPublicId $id -RelativePath 'image.png' -CandidatePath $candidate -CandidateRoot $candidateRoot -ExpectedCandidateHash $new -CandidateImageExtension png -AuthorizationId $binding -AuthorizationRoot $bindingRoot -ExpectedCurrentHash $old -Reason publish -ActorReference test -OperationId $op -CompletedResultPath $commit -FailurePoint CrashAfterReplace)}catch{$actual=$_.Exception.Message};Assert ($actual-eq'INJECTED_PROCESS_CRASH') "Crash injection did not reach post-replace boundary: $actual";Assert ((Hash $sourcePath)-eq$new) 'Crash fixture did not leave replaced source.';$prepared=Get-Content -LiteralPath $commit -Raw|ConvertFrom-Json;Assert ([string]$prepared.status-eq'prepared') 'Prepared publish journal missing.';$rollbackPath=Join-Path (Split-Path -Parent $sourcePath) ('.document-version-rollback-'+$op+'.tmp');Assert (Test-Path -LiteralPath $rollbackPath -PathType Leaf) 'Prepared rollback missing.';$count=Repair-TWWaterPreparedImagePublishes -ImageSourceRoot $source -ImageArchiveRoot $archive -SessionRoot $session;Assert ($count-eq1) 'Prepared publish was not reconciled.';$done=Get-Content -LiteralPath $commit -Raw|ConvertFrom-Json;Assert ([string]$done.status-eq'local-published') 'Recovered publish commit not finalized.';Assert (Test-Path -LiteralPath (Join-Path $bindingRoot ($binding+'.json')) -PathType Leaf) 'Recovered binding marker missing.';Assert (Test-Path -LiteralPath (Join-Path (Join-Path $session 'document-version-approved') ($id.ToLowerInvariant()+'-'+$new+'.json')) -PathType Leaf) 'Recovered approval missing.';Assert (-not(Test-Path -LiteralPath $rollbackPath)) 'Recovered rollback was not removed.';Write-Host '[OK] Prepared image publish is reconciled after a post-replace crash.'}finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
